### PR TITLE
try add osx_arm64 adn linux_aarch64

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is necessary for building QGIS in osx_arm64 and linux_aarch64
https://github.com/conda-forge/qgis-feedstock/pull/289

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
I have hit pull request but it's more of a draft... don't take it too serious :-)

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Ah! It seems it kinda worked. @gillins can you check if this is ok, and if it's useful for the QGIS build?

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
Thanks @SrNetoChan !

**Pull request merged**
